Repository atlp-rwanda/elite-bn-be, pull requests merged in 2022-08, with the labels that each got.

#76 feat(notifications):user should mark all notification as read
  package-lock.json
  public/api-docs/notificaton.yaml
  src/controllers/notificationController.js
  src/routes/notificationRouter.js
  src/services/notificationService.js
  test/AccommodationTripReq.js
Labels: Ready for review

#77 (redis):redis-cluster-fix
  src/controllers/userController.js
  src/middlewares/checkAuth.js
  src/utils/helpers/createToken.js
  src/utils/helpers/initRedis.js
  src/utils/helpers/redis.config.js
  test/AccommodationTripReq.js
  test/chat.spec.js
  test/country.js
  test/logout.js
  test/profile.js
  test/resetPassword.js
Labels: Ready for review

#75 bug-fix-logout
  package.json
  public/api-docs/users.yaml
  src/controllers/accomodation.js
  src/controllers/location.js
  src/controllers/room.js
  src/controllers/userController.js
  src/middlewares/checkAuth.js
  src/routes/userRouter.js
  src/services/userServices.js
  src/utils/helpers/createToken.js
  src/utils/helpers/initRedis.js
  test/AccommodationTripReq.js
  test/chat.spec.js
  test/country.js
  test/logout.js
  test/profile.js
Labels: Ready for review, ready to be merged

#79 fix(social-auth): Users should be able to Login via Facebook and Google.
  src/controllers/googleFacebook.js
  yarn.lock
Labels: Ready for review

#82 fix reset passwor
  public/api-docs/password.yaml
  src/controllers/userController.js
  src/routes/userRouter.js
  src/services/userServices.js
  src/validations/userValidation.js
  test/resetPassword.js
Labels: Ready for review

#84 fix(user-registration): same toke as for the login
  src/controllers/userController.js
  test/user.js
Labels: ready to be merged
