Repository atlp-rwanda/elite-bn-be, pull requests merged in 2022-07, with the labels that each got.

#62 ft(make-trip-request): requester should make a trip request
  package-lock.json
  public/api-docs/trip.yaml
  src/controllers/location.js
  src/controllers/rolesController.js
  src/controllers/room.js
  src/controllers/tripController.js
  src/controllers/userController.js
  src/database/migrations/6-create-trip-request.js
  src/database/models/triprequest.js
  src/database/seeders/user.js
  src/middlewares/managerAuth.js
  src/public/api-docs/index.yaml
  src/public/api-docs/users.yaml
  src/public/api-docs/usersRole.yaml
  src/routes/index.js
  src/routes/trip.js
  src/utils/errors/errorHandle.js
  src/validations/tripValidation.js
  test/AccomodationCRUD.spec.js
Labels: Ready for review

#65 feat(Reject/Approve Request):As a manager, I should be able to reject/approve a request
  package-lock.json
  public/api-docs/trip.yaml
  pull_request_connect_t0_db.md
  src/controllers/accomodation.js
  src/controllers/approveOrRejectRequest.js
  src/controllers/tripController.js
  src/controllers/tripStatistics.js
  src/database/migrations/6-create-trip-request.js
  src/database/models/triprequest.js
  src/routes/approveOrRejectRequest.js
  src/routes/index.js
  src/routes/tripStatistics.js
  src/services/tripStatisticService.js
  src/validations/tripStatValidation.js
  src/validations/tripValidation.js
  test/AccomodationCRUD.spec.js
Labels: Ready for review, Approved, ready to be merged

#66 ft(like-dislike): Users should be able to like/unlike an accommodation facility
  package-lock.json
  package.json
  public/api-docs/like.yaml
  public/api-docs/users.yaml
  src/controllers/likeController.js
  src/database/migrations/9-create-like.js
  src/database/models/like.js
  src/database/seeders/user.js
  src/middlewares/like.js
  src/routes/index.js
  src/routes/likeRouter.js
  src/services/likeService.js
  src/utils/response.js
  src/validations/likeValidation.js
  src/validations/paramsValidate.js
  test/AccomodationCRUD.spec.js
  test/country.spec.js
  test/profile.js
Labels: Ready for review, Approved, ready to be merged

#45 (ft-users-feedback-182201580):Users should be able to provide feedback-182201580
  package.json
  public/api-docs/accomodation.yaml
  src/controllers/feedbackController.js
  src/database/migrations/20220612170434-create-feedback.js
  src/database/models/accomodation.js
  src/database/models/feedback.js
  src/routes/feedbackRouter.js
  src/routes/index.js
  src/services/accomodationService.js
Labels: Ready for review

#69 ft(comment-on-trip): traveler should comment&delete on trip request
  public/api-docs/tripComment.yaml
  src/controllers/tripComment.js
  src/controllers/tripController.js
  src/database/migrations/7-create-trip-comment.js
  src/database/models/tripcomment.js
  src/routes/trip.js
  src/services/tripCommentService.js
  src/validations/tripCommentValidation.js
  test/AccommodationTripReq.js
  test/country.js
  test/index.js
  test/resetPassword.js
  test/user.js
Labels: Ready for review, Approved

#64 feat(Statistics):Users should get stats of trips made in the last timeframe
  package-lock.json
  public/api-docs/trip.yaml
  src/controllers/index.js
  src/controllers/tripStatistics.js
  src/routes/index.js
  src/routes/tripStatistics.js
  src/routes/tripStatisticsRouter.js
  src/services/index.js
  src/services/tripStatServices.js
  src/services/tripStatisticService.js
  src/utils/helpers/responseHandler.js
  test/statistics.spec.js
Labels: Approved, ready to be merged

#71 Fix coverage badge and the tests
  package-lock.json
  package.json
  public/api-docs/trip.yaml
  src/controllers/accomodation.js
  src/controllers/approveOrRejectRequest.js
  src/controllers/feedbackController.js
  src/controllers/index.js
  src/controllers/tripController.js
  src/controllers/tripStatistics.js
  src/database/migrations/20220612170434-create-feedback.js
  src/database/models/feedback.js
  src/routes/approveOrRejectRequest.js
  src/routes/feedbackRouter.js
  src/routes/index.js
  src/routes/tripStatisticsRouter.js
  src/services/accomodationService.js
  src/services/index.js
  src/services/tripStatServices.js
  src/utils/helpers/responseHandler.js
  test/AccommodationTripReq.js
  test/statistics.spec.js
Labels: ready to be merged

#49 feat(most-travelled-destinations):Users should be able to get info on the most frequently travelled centre/destination
  public/api-docs/trip.yaml
  src/controllers/accomodation.js
  src/controllers/tripController.js
  src/routes/accomodationRouter.js
  src/routes/index.js
  src/routes/trip.js
  src/utils/catchAsync.js
  src/utils/errors/applicatioErrors.js
  src/utils/response.js
  test/AccommodationTripReq.js
Labels: Ready for review

#72 ft(Search-functionality): find requests through the search functiona…
  public/api-docs/trip.yaml
  public/api-docs/tripSearch.yaml
  src/controllers/accomodation.js
  src/controllers/feedbackController.js
  src/controllers/tripController.js
  src/controllers/tripRequestsSearchController.js
  src/database/models/triprequest.js
  src/exceptions/index.js
  src/middlewares/searchValidate.js
  src/routes/accomodationRouter.js
  src/routes/index.js
  src/routes/searchRouter.js
  src/routes/trip.js
  src/services/searchTripRequest.js
  src/utils/catchAsync.js
  src/utils/errors/applicatioErrors.js
  src/utils/errors/errorResponse.js
  src/utils/response.js
  src/utils/responses/successResponse.js
  src/validations/searchParamsValidate.js
  src/validations/tripSearch.js
  test/AccommodationTripReq.js
Labels: Ready for review, Approved, ready to be merged

#63 feat:(chat bot):Users should be able to chat on Barefoot Nomad
  package-lock.json
  package.json
  public/api-docs/chat.yaml
  public/chat/chat.html
  public/chat/chat.js
  public/chat/index.html
  public/chat/main.js
  public/chat/socket.io.js
  public/chat/styles.css
  src/app.js
  src/controllers/chatsController.js
  src/database/migrations/20220620085536-create-chats.js
  src/database/models/chats.js
  src/index.js
  src/middlewares/chat.js
  src/routes/userRouter.js
  src/services/userServices.js
  src/utils/chat/message.js
  src/utils/chat/users.js
  src/utils/chat/websocket.io.js
  src/utils/helpers/generateToken.js
  src/validations/chatValidation.js
  test/chat.spec.js
Labels: Ready for review, Approved, ready to be merged

#68 feat(multicity-request):Users should be able to make multi city request
  public/api-docs/trip.yaml
  public/chat/chat.html
  public/chat/chat.js
  public/chat/index.html
  public/chat/main.js
  public/chat/socket.io.js
  public/chat/styles.css
  src/app.js
  src/controllers/accomodation.js
  src/controllers/chatsController.js
  src/controllers/index.js
  src/controllers/tripController.js
  src/database/migrations/20220620085536-create-chats.js
  src/database/models/chats.js
  src/index.js
  src/routes/trip.js
  src/routes/userRouter.js
  src/services/multicityServices.js
  src/services/userServices.js
  src/utils/chat/message.js
  src/utils/chat/users.js
  src/utils/chat/websocket.io.js
  src/utils/helpers/generateToken.js
  src/validations/chatValidation.js
  src/validations/multicityValidation.js
  test/AccommodationTripReq.js
  test/chat.spec.js
Labels: Ready for review, Approved, ready to be merged

#70 feat(rating-accomodation): Users should be able to rate a centre
  package-lock.json
  public/api-docs/rating.yaml
  src/controllers/accomodation.js
  src/controllers/rateController.js
  src/database/migrations/.DS_Store
  src/database/migrations/20220706135902-create-rates.js
  src/database/models/.DS_Store
  src/database/models/rates.js
  src/middlewares/.DS_Store
  src/routes/index.js
  src/routes/ratingRouter.js
  src/services/ratingService.js
  src/utils/helpers/rateQueries.js
  src/validations/rateAccommValidation.js
  test/AccommodationTripReq.js
Labels: Ready for review, Approved, ready to be merged

#61 Ft user should logout 182201571 redis-fix
  package-lock.json
  package.json
  public/api-docs/users.yaml
  src/controllers/feedbackController.js
  src/controllers/userController.js
  src/middlewares/checkAuth.js
  src/utils/helpers/createToken.js
  src/utils/helpers/initRedis.js
  src/utils/helpers/redis.config.js
  test/AccommodationTripReq.js
  test/logout.js
Labels: Ready for review, Approved, ready to be merged

#67 ft(Book-accomodation):Users should be able to book an room in an accommodation facility
  package-lock.json
  package.json
  public/api-docs/booking.yaml
  src/controllers/bookingController.js
  src/controllers/feedbackController.js
  src/controllers/room.js
  src/database/migrations/20220717082235-create-booking-room.js
  src/database/migrations/4-create-room.js
  src/database/migrations/8-create-like.js
  src/database/models/bookingroom.js
  src/database/models/room.js
  src/database/models/user.js
  src/middlewares/searchValidate.js
  src/routes/bookingRouter.js
  src/routes/index.js
  src/routes/searchRouter.js
  src/services/bookServices.js
  src/services/roomService.js
  src/services/tripStatServices.js
  src/utils/helpers/bookingDuration.js
  src/validations/multicityValidation.js
  src/validations/paramsValidate.js
  src/validations/searchParamsValidate.js
  src/validations/tripStatValidation.js
  test/AccommodationTripReq.js
  test/chat.spec.js
Labels: Ready for review, Approved, ready to be merged
